# SPDX-FileCopyrightText: © 2026 Peter Lemenkov
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "pyoracle"
SPDX-PackageSupplier = "Peter Lemenkov <lemenkov@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/lemenkov/pyoracle"

[[annotations]]
path = ["README.md", "docs/PROTOCOL.md", "CONTRIBUTING.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Peter Lemenkov <lemenkov@gmail.com>"
SPDX-License-Identifier = "MIT"
